### ISSUE TITLE
Framebuffer does not refresh and loads of StackOverflowError

### ISSUE THREAD

**Issue by zDEFz** [firstfault/Trinity#8]
## Environment # 
- Distribution `Archlinux latest`
- WM: `X11, i3wm`
- JAVA SDK: `17.0.10.fx-zulu`

# How to reproduce #

1. Launch via `java -jar Trinity-0.0.1-alpha1.jar` 
Since no window rule is set, application starts in Tiled Fullscreen mode.
2. Make a new Project and input path is just the cultris2.jar from https://github.com/zDEFz/c2-patch/raw/e63adf684a46877efd3fd3cdf2cd8e898bf1a5c4/cultris2.jar
3. Toggle Window to Floating Window
4. Notice Application does not update the Framebuffer and becomes entirely black
5. Notice StackOverFlow Error
6. https://0x0.st/XH1u.txt

## Notes ##
- Works in Recaf 2 and others without issues.
- I do believe some of the issues is correlated to IMGUI.

**Comment by firstfault** [comment]
Hi! Thanks for reporting this issue. It appears to be an issue of ImGui-Java.

Could you please build the master branch and let me know if this still persists?

**Comment by zDEFz** [comment]
> Hi! Thanks for reporting this issue. It appears to be an issue of ImGui-Java.
> 
> Could you please build the master branch and let me know if this still persists?

It works. I got some debugging info that I wanted to share

Additionally, I'd like to give some Feedback in regards of the bytecode editing feature.
In https://github.com/firstfault/Trinity/blob/master/PLANNED.md , if I read that correctly ...
What is not planned is a bytecode editor that works a bit like a text editor.

Doing lots of changes, and really disliking the mousing operations, such feature would be of great value.
Thanks.

```bash

% java -jar ./build/libs/Trinity.jar
AppDataManager#loadFromFile ERROR Failed to load AppData file preferences: com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$UnknownFieldException: No such field me.f1nal.trinity.appdata.PreferencesFile.decompilerFontEnum
---- Debugging information ----
message             : No such field me.f1nal.trinity.appdata.PreferencesFile.decompilerFontEnum
field               : decompilerFontEnum
class               : me.f1nal.trinity.appdata.PreferencesFile
required-type       : me.f1nal.trinity.appdata.PreferencesFile
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /preferences/decompilerFontEnum
line number         : 2
version             : not available
-------------------------------
```

**Comment by firstfault** [comment]
Thank you for confirming.

About the bytecode editing (assembler) window, it is far from the stage I would like it to be at. A purely text-based assembler would be a lot of pain to work with if you are viewing obfuscated code. However, I still plan to improve functionality in a way similar to a text-based editor and therefore remove the need of insert/edit dialog and such. This will most likely be finished in the next release.

If I may ask, are you referring to mousing operations inside the assembler or in different parts of the application?

I appreciate the feedback!

**Comment by zDEFz** [comment]
Correct, the assembler.
Yea, I appreciate your work.
Hoping to use it for understanding better what I am looking at.
